defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

main:
  input_dir: "C:/WorkingData/Documents/2_Coding/Python/pressure_curve_processing/test"
  output_dir_data: "C:/WorkingData/Documents/2_Coding/Python/pressure_curve_processing/test/processed"
  output_dir_ivus: "C:/WorkingData/Documents/2_Coding/Python/pressure_curve_processing/output/ivus"
