defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

ifr:
  model: "resnet18"
  num_classes: 10
  batch_size: 64
  num_workers: 4
  lr: 0.001
  max_epochs: 10
  seed: 42
  log frequency: 100